POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Enterprise software is frustrating",
  "author": "Bilbo Baggins",
  "url": "http://happy-life.com/gahsd13261234",
  "likes": "12"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Great software books for new software devs",
  "author": "Andrew Garfield",
  "url": "http://happy-life.com/1713417gasd",
  "likes": "22"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Interesting facts of low level programming",
  "author": "Stewert Little",
  "url": "http://happy-life.com/aghagasdf12345",
  "likes": "50"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "DynamoDingo",
  "name": "John Weedham",
  "password": "123456qwerty"
}

###

POST http://localhost:3003/api/users
Content-Type:  application/json

{
  "username": "Electabuzz",
  "name": "David Truman",
  "password": "password"
}
